package xxxt.bilogin.db.entities;
// Generated Jul 24, 2016 7:45:18 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Altmenu generated by hbm2java
 */
public class Altmenu  implements java.io.Serializable {


     private BigDecimal id;
     private String altmenuadi;
     private BigDecimal anamenuId;
     private BigDecimal iconId;
     private String url;

    public Altmenu() {
    }

	
    public Altmenu(BigDecimal id) {
        this.id = id;
    }
    public Altmenu(BigDecimal id, String altmenuadi, BigDecimal anamenuId, BigDecimal iconId, String url) {
       this.id = id;
       this.altmenuadi = altmenuadi;
       this.anamenuId = anamenuId;
       this.iconId = iconId;
       this.url = url;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getAltmenuadi() {
        return this.altmenuadi;
    }
    
    public void setAltmenuadi(String altmenuadi) {
        this.altmenuadi = altmenuadi;
    }
    public BigDecimal getAnamenuId() {
        return this.anamenuId;
    }
    
    public void setAnamenuId(BigDecimal anamenuId) {
        this.anamenuId = anamenuId;
    }
    public BigDecimal getIconId() {
        return this.iconId;
    }
    
    public void setIconId(BigDecimal iconId) {
        this.iconId = iconId;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


