package xxxt.bilogin.db.entities;
// Generated Jun 23, 2016 7:16:46 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Entity;
import javax.persistence.Id;

import javax.persistence.Table;
import org.hibernate.annotations.NamedNativeQueries;
import org.hibernate.annotations.NamedNativeQuery;

/**
 * DimErpOrganizasyonDwhId generated by hbm2java
 */

@Entity
@Table(name="DIM_ERP_ORGANIZASYON_DWH_XT"
)
public class ErpOrganizasyon implements java.io.Serializable {

    @Id
    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    private Long locationId;
    private String locationCode;
    private String description;
    private String townOrCity;
    private Long organizationId;
    private String name;
    private String organizationCode;
    private String glYerlesim;

    public ErpOrganizasyon() {
    }

    public ErpOrganizasyon(Long id,Long locationId, String locationCode, String description, String townOrCity, Long organizationId, String name, String organizationCode, String glYerlesim) {
        this.id=id;
        this.locationId = locationId;
        this.locationCode = locationCode;
        this.description = description;
        this.townOrCity = townOrCity;
        this.organizationId = organizationId;
        this.name = name;
        this.organizationCode = organizationCode;
        this.glYerlesim = glYerlesim;
    }

    public Long getLocationId() {
        return this.locationId;
    }

    public void setLocationId(Long locationId) {
        this.locationId = locationId;
    }

    public String getLocationCode() {
        return this.locationCode;
    }

    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getTownOrCity() {
        return this.townOrCity;
    }

    public void setTownOrCity(String townOrCity) {
        this.townOrCity = townOrCity;
    }

    public Long getOrganizationId() {
        return this.organizationId;
    }

    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getOrganizationCode() {
        return this.organizationCode;
    }

    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode;
    }

    public String getGlYerlesim() {
        return this.glYerlesim;
    }

    public void setGlYerlesim(String glYerlesim) {
        this.glYerlesim = glYerlesim;
    }

   
}
