package xxxt.bilogin.db.entities;
// Generated Jun 10, 2016 11:36:38 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KullaniciXt generated by hbm2java
 */
@Entity
@Table(name="KULLANICI"
)
public class Kullanici  implements java.io.Serializable {

 
     private int id;
     private String kullaniciadi;
     private String ad;
     private String soyad;
     private String adsoyad;
     private String sifre;
     private String sicilno;
     private String tcno;
     private String organizasyonId;
     private BigDecimal kisiid;
     private String eposta;     
     private String isletmetipi;
     private String kaydiyapankullanici;
     private String kaydiguncelleyenkullanici;
     private BigDecimal isletmetipiId;
     private String isletmeadi;
     private String calistigibirim;     
     private Boolean aktif;
     private String yerlesimkod;
     private String orgKod;
     private String name;     
     private Date kayiteklemetarihi;
     private Date kayitguncellemetarihi;
     private BigDecimal personelTip;
     private Boolean isyazilim;
     private String unvan;
     private Boolean sifreDegistir;
     private String organizationId;

    public String getOrganizationId() {
        return organizationId;
    }

    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    public Kullanici() {
    }

	
    public Kullanici(int id) {
        this.id = id;
    }
    public Kullanici(int id, String kullaniciadi, String ad, String soyad, String adsoyad, String sifre, String sicilno, String tcno, String organizasyonId, BigDecimal kisiid, String eposta, String isletmetipi, String kaydiyapankullanici, String kaydiguncelleyenkullanici, BigDecimal isletmetipiId, String isletmeadi, String calistigibirim,  Boolean aktif, String yerlesimkod, String orgKod, String name, Date kayiteklemetarihi, Date kayitguncellemetarihi, BigDecimal personelTip, Boolean isyazilim, String unvan) {
       this.id = id;
       this.kullaniciadi = kullaniciadi;
       this.ad = ad;
       this.soyad = soyad;
       this.adsoyad = adsoyad;
       this.sifre = sifre;
       this.sicilno = sicilno;
       this.tcno = tcno;
       this.organizasyonId = organizasyonId;
       this.kisiid = kisiid;
       this.eposta = eposta;
       
       this.isletmetipi = isletmetipi;
       this.kaydiyapankullanici = kaydiyapankullanici;
       this.kaydiguncelleyenkullanici = kaydiguncelleyenkullanici;
       this.isletmetipiId = isletmetipiId;
       this.isletmeadi = isletmeadi;
       this.calistigibirim = calistigibirim;       
       this.aktif = aktif;
       this.yerlesimkod = yerlesimkod;
       this.orgKod = orgKod;
       this.name = name;       
       this.kayiteklemetarihi = kayiteklemetarihi;
       this.kayitguncellemetarihi = kayitguncellemetarihi;
       this.personelTip = personelTip;
       this.isyazilim = isyazilim;
       this.unvan = unvan;
    }
   
     @Id 
    
    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    

    public String getKullaniciadi() {
        return this.kullaniciadi;
    }
    
    public void setKullaniciadi(String kullaniciadi) {
        this.kullaniciadi = kullaniciadi;
    }
    

    public String getAd() {
        return this.ad;
    }
    
    public void setAd(String ad) {
        this.ad = ad;
    }
    
   
    public String getSoyad() {
        return this.soyad;
    }
    
    public void setSoyad(String soyad) {
        this.soyad = soyad;
    }
    
  
    public String getAdsoyad() {
        return this.adsoyad;
    }
    
    public void setAdsoyad(String adsoyad) {
        this.adsoyad = adsoyad;
    }
    
  
    public String getSifre() {
        return this.sifre;
    }
    
    public void setSifre(String sifre) {
        this.sifre = sifre;
    }
    
  
    public String getSicilno() {
        return this.sicilno;
    }
    
    public void setSicilno(String sicilno) {
        this.sicilno = sicilno;
    }
    
  
    public String getTcno() {
        return this.tcno;
    }
    
    public void setTcno(String tcno) {
        this.tcno = tcno;
    }
    

    public String getOrganizasyonId() {
        return this.organizasyonId;
    }
    
    public void setOrganizasyonId(String organizasyonId) {
        this.organizasyonId = organizasyonId;
    }
    
    
    public BigDecimal getKisiid() {
        return this.kisiid;
    }
    
    public void setKisiid(BigDecimal kisiid) {
        this.kisiid = kisiid;
    }
    
   
    public String getEposta() {
        return this.eposta;
    }
    
    public void setEposta(String eposta) {
        this.eposta = eposta;
    }
    
   
    
    
  
    public String getIsletmetipi() {
        return this.isletmetipi;
    }
    
    public void setIsletmetipi(String isletmetipi) {
        this.isletmetipi = isletmetipi;
    }
    
  
    public String getKaydiyapankullanici() {
        return this.kaydiyapankullanici;
    }
    
    public void setKaydiyapankullanici(String kaydiyapankullanici) {
        this.kaydiyapankullanici = kaydiyapankullanici;
    }
    
  
    public String getKaydiguncelleyenkullanici() {
        return this.kaydiguncelleyenkullanici;
    }
    
    public void setKaydiguncelleyenkullanici(String kaydiguncelleyenkullanici) {
        this.kaydiguncelleyenkullanici = kaydiguncelleyenkullanici;
    }
    
  
    public BigDecimal getIsletmetipiId() {
        return this.isletmetipiId;
    }
    
    public void setIsletmetipiId(BigDecimal isletmetipiId) {
        this.isletmetipiId = isletmetipiId;
    }
    
    
    public String getIsletmeadi() {
        return this.isletmeadi;
    }
    
    public void setIsletmeadi(String isletmeadi) {
        this.isletmeadi = isletmeadi;
    }
    
   
    public String getCalistigibirim() {
        return this.calistigibirim;
    }
    
    public void setCalistigibirim(String calistigibirim) {
        this.calistigibirim = calistigibirim;
    }
    

   
   
    
    
    public Boolean getAktif() {
        return this.aktif;
    }
    
    public void setAktif(Boolean aktif) {
        this.aktif = aktif;
    }
    
  
    public String getYerlesimkod() {
        return this.yerlesimkod;
    }
    
    public void setYerlesimkod(String yerlesimkod) {
        this.yerlesimkod = yerlesimkod;
    }
    
   
    public String getOrgKod() {
        return this.orgKod;
    }
    
    public void setOrgKod(String orgKod) {
        this.orgKod = orgKod;
    }
    
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
   
    
    @Temporal(TemporalType.DATE)
    
    public Date getKayiteklemetarihi() {
        return this.kayiteklemetarihi;
    }
    
    public void setKayiteklemetarihi(Date kayiteklemetarihi) {
        this.kayiteklemetarihi = kayiteklemetarihi;
    }
    @Temporal(TemporalType.DATE)
  
    public Date getKayitguncellemetarihi() {
        return this.kayitguncellemetarihi;
    }
    
    public void setKayitguncellemetarihi(Date kayitguncellemetarihi) {
        this.kayitguncellemetarihi = kayitguncellemetarihi;
    }
    
    
    public BigDecimal getPersonelTip() {
        return this.personelTip;
    }
    
    public void setPersonelTip(BigDecimal personelTip) {
        this.personelTip = personelTip;
    }
    

    public Boolean getIsyazilim() {
        return this.isyazilim;
    }
    
    public void setIsyazilim(Boolean isyazilim) {
        this.isyazilim = isyazilim;
    }
    
  
    public String getUnvan() {
        return this.unvan;
    }
    
    public void setUnvan(String unvan) {
        this.unvan = unvan;
    }
    
    public Boolean getSifreDegistir() {
        return sifreDegistir;
    }

    public void setSifreDegistir(Boolean sifreDegistir) {
        this.sifreDegistir = sifreDegistir;
    }

}


